# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RRI_cpp <- function(x, ni, nw) {
    .Call(`_SurfRough_RRI_cpp`, x, ni, nw)
}

RRIK3_cpp <- function(x, ni, nw) {
    .Call(`_SurfRough_RRIK3_cpp`, x, ni, nw)
}

RRIMin_cpp <- function(x, ni, nw) {
    .Call(`_SurfRough_RRIMin_cpp`, x, ni, nw)
}

RRIMax_cpp <- function(x, ni, nw) {
    .Call(`_SurfRough_RRIMax_cpp`, x, ni, nw)
}

